### ISSUE TITLE
Menu on Intro page

### ISSUE THREAD

**Issue by fiddleHeads** [ubc-library-rc/intro-to-arcgis-pro#1]
The first three pages don't work from the Menu at the top of the Introduction page.

**Comment by ect123** [comment]
Do you object to just removing that menu? I think that's a relic leftover from previous formats of these GitHub workshops (pre-Just-the_Docs theme). If not then I'll fix those links.

**Comment by fiddleHeads** [comment]
That sounds good. I just deleted the menu. Thanks.
