### ISSUE TITLE
Making certain pages invisible

### ISSUE THREAD

**Issue by fiddleHeads** [ubc-library-rc/intro-to-arcgis-pro#2]
Is it possible to turn off visibility for the Labels and Add Data pages? I don't want to include them in this workshop but don't want to throw away the work in case it comes in handy in the future.

**Comment by ect123** [comment]
I commented out the front matter to keep it from appearing in the menu navigation, although those pages are still in the repo and published: https://ubc-library-rc.github.io/intro-to-arcgis-pro/content/add-data.html
https://ubc-library-rc.github.io/intro-to-arcgis-pro/content/labels.html
When you're ready to have them appear, you can remove the comment syntax I used: [//]: # (Comment)
